import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * Generates a dynamic PDF report for the EMR Health Center.
 * 
 * @param {Object} options
 * @param {string} options.title - Title of the report (e.g., "Disease Report")
 * @param {string} options.monthYear - Month and year string (e.g., "June 2025")
 * @param {string[]} options.tableHeaders - Array of column headers
 * @param {Array[]} options.tableData - 2D array for table rows (arrays of strings/numbers)
 * @param {string} [options.logo] - Optional image path or base64 for logo
 */
export function generatePDF({ title, monthYear, tableHeaders, tableData, logo }) {
  const doc = new jsPDF('portrait', 'mm', 'a4'); // Portrait, millimeters, A4
  const marginLeft = 14;

  // Optional logo
  if (logo) {
    const image = new Image();
    image.src = logo;
    image.onload = () => {
      doc.addImage(image, 'PNG', 150, 15, 40, 15); // Top right logo
      drawContent();
    };
  } else {
    drawContent();
  }

  function drawContent() {
    // --- Header Section ---
    doc.setFontSize(16);
    doc.setFont('times', 'bold');
    doc.text('Karangalan Health Center', marginLeft, 20);

    doc.setFontSize(12);
    doc.setFont('times', 'normal');
    doc.text(`Report Type: ${title}`, marginLeft, 30);
    doc.text(`Reporting Period: ${monthYear}`, marginLeft, 36);

    // --- Table Section ---
    autoTable(doc, {
      startY: 50,
      head: [tableHeaders],
      body: tableData.length > 0 ? tableData : [['No data available']],
      theme: 'grid',
      headStyles: {
      fillColor: [0, 188, 212],
      halign: 'center',
      font: 'times',
      fontStyle: 'bold',
      },
      styles: {
      fontSize: 10,
      cellPadding: 3,
      halign: 'center',
      font: 'Arial',
      fontStyle: 'normal',
      },
    });

    // --- Footer or Notes (Optional) ---
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100); // Lighter color for footer
    doc.text('Generated by Medika System | Timezone: Asia/Manila', marginLeft, doc.internal.pageSize.height - 10);

    // --- Save PDF ---
    const filename = `${title} ${monthYear}.pdf`;
    doc.save(filename);
  }
}