import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * Generates a dynamic multi-section PDF report for the EMR Health Center.
 * 
 * @param {Object} options
 * @param {string} options.title - Overall report title
 * @param {string} options.monthYear - Month and year string (e.g., "June 2025")
 * @param {Array} options.sections - Array of section objects { sectionTitle, tableHeaders, tableData }
 * @param {string} [options.logo] - Optional image path or base64 for logo
 */
export function generatePDF({ title, monthYear, sections, logo }) {
  const doc = new jsPDF('portrait', 'mm', 'a4');
  const marginLeft = 14;
  let currentY = 20;

  function drawContent() {
    // --- Header Section ---
    doc.setFontSize(16);
    doc.setFont('times', 'bold');
    doc.text('Karangalan Health Center', marginLeft, currentY);

    currentY += 10;
    doc.setFontSize(12);
    doc.setFont('times', 'normal');
    doc.text(`Report Type: ${title}`, marginLeft, currentY);
    currentY += 6;
    doc.text(`Reporting Period: ${monthYear}`, marginLeft, currentY);
    currentY += 10;

    // --- Each Section ---
    sections.forEach((section, index) => {
      if (currentY >= 260) {
        doc.addPage();
        currentY = 20;
      }

      doc.setFontSize(13);
      doc.setFont('times', 'bold');
      doc.text(section.sectionTitle, marginLeft, currentY);
      currentY += 6;

      autoTable(doc, {
        startY: currentY,
        head: [section.tableHeaders],
        body: section.tableData.length > 0 ? section.tableData : [['No data available']],
        theme: 'grid',
        margin: { left: marginLeft, right: marginLeft },
        headStyles: {
          fillColor: [0, 188, 212],
          halign: 'center',
          font: 'times',
          fontStyle: 'bold',
        },
        styles: {
          fontSize: 10,
          cellPadding: 3,
          halign: 'center',
          font: 'Arial',
          fontStyle: 'normal',
        },
        didDrawPage: (data) => {
          currentY = data.cursor.y + 10;
        },
      });

      if (index < sections.length - 1 && currentY >= 240) {
        doc.addPage();
        currentY = 20;
      }
    });

    // --- Footer ---
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100);
    doc.text('Generated by Medika System | Timezone: Asia/Manila', marginLeft, doc.internal.pageSize.height - 10);

    doc.save(`${title} ${monthYear}.pdf`);
  }

  // --- Handle logo loading async ---
  if (logo) {
    const image = new Image();
    image.src = logo;
    image.onload = () => {
      doc.addImage(image, 'PNG', 150, 15, 40, 15); // Top right
      drawContent();
    };
  } else {
    drawContent();
  }
}
